"""Added Champ autoincrement

Revision ID: 76e3d0cf4a87
Revises: 2c4d4895bb89
Create Date: 2020-09-27 01:01:52.004097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e3d0cf4a87'
down_revision = '2c4d4895bb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
